language: node_js
node_js:
  - '10.0'

dist: trusty
sudo: false

before_deploy:
  npm run-script build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: "ttkamerat.fi"
  skip_cleanup: false
  local_dir: public
  region: eu-west-1
  acl: public_read